services:
  # Backend service
  - type: web
    name: tesystem
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node seed.js && node app.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODBURL
        sync: false # User will provide this
      - key: KEY
        generateValue: true
      - key: PORT
        value: 5000

  # Frontend service
  - type: web
    name: tesystem-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_BACKEND_URL
        value: https://tesystem.onrender.com/api
